### ISSUE TITLE
Class decorator return types overriden by plugin.

### ISSUE THREAD

**Issue by Numerlor** [koxudaxi/pydantic-pycharm-plugin#558]
**Describe the bug**
Return types of decorators on pydantic models are ignored and the names are always treated as model classes instead of what the decorator returns.
The auto completion of the fields also seems to be broken
**To Reproduce**
```py
from pydantic import BaseModel


def deco(_) -> None:
    return

@deco
class WrongType(BaseModel):
    a: int

a = WrongType()  # shouldn't work as a call
```

**Expected behavior**
The decorated class to have the correct type, instead of being treated as the BaseModel subclass.

**Screenshots**
Also, gif movies are recommended.

**Environments (please complete the following information):**
 - IDE: PyCharm Community 2022.2.2
 - OS: win 10
 - Pydantic Version: 1.9.1
 - Plugin version: 0.3.13

**Comment by koxudaxi** [comment]
@Numerlor 
Thank you for the issue.
I guess the problem is not a bug in the plugin.
Because PyCharm can't detect actual decorated classes.
<img width="336" alt="Screenshot 2022-12-12 at 14 54 21" src="https://user-images.githubusercontent.com/630670/206970705-6a2867f6-0de5-4da7-a8a5-5d94996aab6f.png">

**Comment by koxudaxi** [comment]
@Numerlor 
You should report it to the JetBrains tracker.
https://youtrack.jetbrains.com/issues
