### ISSUE TITLE
support "pre-configured" dataclass class decorators

### ISSUE THREAD

**Issue by amenck** [koxudaxi/pydantic-pycharm-plugin#638]
**Describe the bug**
If we use a pre-defined custom dataclass decorator to create dataclasses, the resulting dataclasses (while entirely valid in python) will receive any of the benefits of this package.

**To Reproduce**
Consider the following repro:
```python
from pydantic.dataclasses import dataclass


class MyDataclassConfig:
    arbitrary_types_allowed = True


my_dataclass_decorator = dataclass(frozen=True, config=MyDataclassConfig)


@my_dataclass_decorator
class ThisWontWork:
    this_is_an_int: int


_ = ThisWontWork(this_is_a_str=20)
```
The "custom decorator" `my_dataclass_decorator` works perfectly well in python, and is a pattern we often use in order to "standardize" our dataclasses configs. However, the dataclass generated (`ThisWontDork`) ends up not benefiting from all the helpful functionality of this plugin.

**Expected behavior**
I'd expect my generated dataclass in the example above to benefit from all the nice functionality in this plugin.

**Screenshots**
See how only the second instantiation catches that something is wrong:
<img width="643" alt="Screen Shot 2023-01-30 at 7 58 39 PM" src="https://user-images.githubusercontent.com/11997462/215660355-5525cca1-faf7-4377-86b3-9d5d51ad10b8.png">

**Environments (please complete the following information):**
 - IDE: PyCharm Community 2022.3
 - OS: macOs 12.5
 - Pydantic Version: 1.10.4
 - Plugin version: 0.3.17

**Comment by koxudaxi** [comment]
@amenck 
I'm sorry for my too-late reply.
The problem comes from PyCharm.
The plugin uses the dataclass feature of PyCharm.
I tried to use the same sample code with `dataclasses.dataclass`. And I found the same problem.
Could you please fix the problem for JetBrains? 
https://youtrack.jetbrains.com/issues

![image](https://user-images.githubusercontent.com/630670/221234021-d221b1a2-618e-4afd-9c9f-acaaece64f05.png)
