### ISSUE TITLE
@model_validator(mode="before") causes "Problematic nesting of decorators" inspection false positive

### ISSUE THREAD

**Issue by skewty** [koxudaxi/pydantic-pycharm-plugin#871]
Prevent **Problematic nesting of decorators** built-in Python inspection *false positive* when using `@model_validator(mode="before")`. 

NOTE: linter can be made happy again by using `# noinspection PyNestedDecorators`.

```python
from pydantic import BaseModel, model_validator

class Foo(BaseModel):
    value: int

    # noinspection PyNestedDecorators
    @model_validator(mode="before")
    @classmethod
    def whatever(cls, data):
        return data

```

**Comment by skewty** [comment]
Wow, you resolved that one quickly; much appreciated.  Sincere thank you.

**Comment by koxudaxi** [comment]
> Wow, you resolved that one quickly; much appreciated. Sincere thank you.

There are two clear reasons.
- Because you are the sponsor. We want to give back as much as possible.
- Because we knew how to fix it. When it comes to plugin development, we spend a lot of time and effort looking for implementation approaches rather than coding.

I will release the next version this week.
Thank you for your help :smile:
